### ISSUE TITLE
Fixed error and added Edge Browser cookie grabber

### ISSUE THREAD

**Issue by Stanley-GF** [TheBackdoor/CockyGrabber#1]
Hi,
Just making a MAJ if u want,

### **FIXED :** 

- All error of "find not found"

### **Updata :**

- Edge browser cookie stealer
[CockyGrabber.zip](https://github.com/TheBackdoor/CockyGrabber/files/5504848/CockyGrabber.zip)

**Comment by TheBackdoor** [comment]
Thank you very much. I will implement it in the rep.

**Comment by TheBackdoor** [comment]
Hm. Doesn't work. Values are not in the cookie File.
and I found this files too: C:\Users\UserName\AppData\Local\Packages\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\AC\#!001\MicrosoftEdge\Cookies
:/

**Comment by Stanley-GF** [comment]
Hi,
Yeah sorry, I just forgot a detail.
I attach "Edge" to you as an attachment (Normally fixed).

Oh, and did you have a discord ? 

Regards, 
Stan

[EdgeBrowser.zip](https://github.com/TheBackdoor/CockyGrabber/files/5506047/EdgeBrowser.zip)

**Comment by TheBackdoor** [comment]
k. thank you. I will work on it later then!
and yes I have discord: N O T H I N G#3392
